apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cnpvxo84b-go
  janus-idp.io/tekton: cnpvxo84b-go
  backstage.io/kubernetes-id: cnpvxo84b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cnpvxo84b-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
